### PR TITLE
Let's make a new release.

### PR DESCRIPTION
**Pull request by akhilman**
Let's make new 0.2.0 release. #33 

Main changes:

### Complite lock refactoring.

Implementing instance.set_lock() and instance.unset_lock()
as lua scripts with additional checks on server side.

Solves:
 * #16 Possible wrong behaviour in case partial lock
 * #10 Ensure futures and gather them to lock the instances

### Aioredlock.extend(lock) to extend lock lifetime

Solves:
 * #15 Provide a way to extend an already acquired lock for more time

### Raising exceptions on fault.

Introduces aioredlock.LockError.
All three functions: lock(), extend(), unlock() will raise this exception in case of fault.

Solves:
 * #6 Raise an exception if the lock cannot be obtained for any reason

### Locking with context manager

Introduces async context manager interface for Lock class

```python
async with await lockmanager.lock('resource') as lock:
    assert lock.valid
    do_something
    await lock.extend()  # add more time
    do_more
assert not lock.valid  # here lock should be unlocked by context manager
```
Also Lock.extend() aliased to lock_manager.extend(lock)

Solves:
 * #19 Locking with context manager

### Support same address format as aioredis

Every connection now can be one of the following:
- a dict like {'host': 'localhost', 'port': 6379, 'db': 0, 'password': 'pass'} all keys except host and port will be passed as kwargs to aioredis.create_redis_pool();
- a Redis URI - "redis://host:6379/0?encoding=utf-8";
- a (host, port) tuple - ('localhost', 6379);
- or a unix domain socket path string - "/path/to/redis.sock".

Solves:
 * #25 Support same address format as aioredis

### Aioredlock.destroy() now con be called w/o connection

Before this changes in `Redis.clear_connection()` `Aioredlock.destroy()` did caused the exception if there is no initialized connections to redis instances.

Now we will check is `Instance` connected before trying to clear connection.

### Aioredlock.is_locked() to check is lock acquired

Aioredlock.is_locked() is checking if the resource is acquired by another lock manager.

May be solves #23 Track lock's lifetime in Lock instances

### The ``lock_timeout`` and ``drift`` parameters now measured in seconds,
   
Solves:
 * #32 Use same units for lock_timeout and retry_delay

### Simulating multiple Redis instances using Redis ``db`` parameter.

With this update we can run full acceptance test with CI.

Solves:
  * #26 Use same redis instance with different db for CI tests

### CODE REVIEW

**Comment by akhilman** [comment]
Date in changelog should be updated before making new release.

**Comment by owaaa** [comment]
bump, releasing to pypi soon?

**Comment by akhilman** [comment]
I have access to a git master, but only @joanvila have a key to make pip release.
For now I'm using git link in my `requirements.txt`
```
git+https://github.com/akhilman/aioredlock.git@master#egg=aioredlock
```

**Comment by joanvila** [comment]
Done! Amazing work @akhilman, sorry for the delay...
https://pypi.python.org/pypi?:action=display&name=aioredlock&version=0.2.0

**Comment by akhilman** [comment]
Thanks!

**Pull request merged**
